CREATE OR REPLACE FUNCTION TRIGGER_ALBUM_CIRCULAR()
    RETURNS TRIGGER
AS $$
DECLARE _ARTISTA_PRINCIPAL  VARCHAR(100);
BEGIN
    SELECT A.ARTISTA INTO _ARTISTA_PRINCIPAL FROM ALBUM A 
        WHERE A.ID_ALBUM = NEW.ID_ALBUM;

    IF (_ARTISTA_PRINCIPAL = NEW.PARTICIPANTE) THEN
        RAISE EXCEPTION 'Artista % ja eh principal do album',
            _ARTISTA_PRINCIPAL;
        RETURN NULL;
    END IF;

    RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;
