CREATE OR REPLACE FUNCTION TRIGGER_BLOQUEIA_BANIDOS()
    RETURNS TRIGGER
AS $$
BEGIN
    IF EXISTS (SELECT * FROM BANIDO_POR BP
        WHERE UPPER(BP.USUARIO_BANIDO) = UPPER(NEW.NOME_USUARIO)) THEN
            RAISE EXCEPTION '% não pode executar essa ação porque está banido',
                NEW.NOME_USUARIO;
            RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
