CREATE OR REPLACE FUNCTION TRIGGER_CLASSIFICA_POR_TAG_REMOVIDA()
    RETURNS TRIGGER
AS $$
BEGIN
    IF EXISTS (SELECT * FROM TAG_REMOVIDA TR WHERE 
        TR.MUSICA = NEW.ID_MUSICA AND UPPER(TR.TAG) = UPPER(NEW.TAG)) THEN
            RAISE EXCEPTION 'Tag % nao pode ser inserida nessa musica',
                NEW.TAG;
            RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
