CREATE OR REPLACE FUNCTION TRIGGER_PERMISSAO_BAN()
    RETURNS TRIGGER
AS $$
DECLARE _CARGO_MOD  CHAR(1);
        _CARGO_USR  CHAR(1);
BEGIN
    SELECT U.CARGO INTO _CARGO_MOD FROM USUARIO U
        WHERE U.NOME_USUARIO = NEW.MODERADOR;

    SELECT U.CARGO INTO _CARGO_USR FROM USUARIO U
        WHERE U.NOME_USUARIO = NEW.USUARIO_BANIDO;

    IF ((_CARGO_MOD = 'M' AND _CARGO_USR NOT IN ('M', 'A')) 
        OR (_CARGO_MOD = 'A')) THEN
            RETURN NEW;
    ELSE
        RAISE EXCEPTION '% nao possui permissao para banir %',
            NEW.MODERADOR, NEW.USUARIO_BANIDO;
        RETURN NULL;
    END IF;
END;
$$
LANGUAGE PLPGSQL;
