CREATE OR REPLACE FUNCTION TRIGGER_PERMISSAO_REMOVE()
    RETURNS TRIGGER
AS $$
DECLARE _CARGO_MOD  CHAR(1);
BEGIN
    SELECT U.CARGO INTO _CARGO_MOD FROM USUARIO U
        WHERE U.NOME_USUARIO = NEW.MODERADOR;

    IF (_CARGO_MOD NOT IN ('M', 'A')) THEN
        RAISE EXCEPTION '% nao possui permissao para remover', NEW.MODERADOR;
        RETURN NULL;
    END IF;

    RETURN NEW;
END;
$$
LANGUAGE PLPGSQL;

