CREATE OR REPLACE FUNCTION TRIGGER_TAG_REMOVER_CONSISTENTE()
    RETURNS TRIGGER
AS $$
DECLARE _T_COUNT INTEGER;
BEGIN
    SELECT COUNT(*) INTO _T_COUNT FROM CLASSIFICA_POR CP 
        WHERE UPPER(CP.TAG) = UPPER(NEW.TAG) AND CP.ID_MUSICA = NEW.MUSICA;
    
    IF _T_COUNT = 0 THEN
            RAISE EXCEPTION 'A tag % a ser removida, para a musica em questao, nao existe',
                NEW.TAG;
            RETURN NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE PLPGSQL;
