CREATE TABLE USUARIO (
    NOME_USUARIO    VARCHAR(50),
    EH_CRITICO      BOOLEAN     NOT NULL,
    EMAIL           VARCHAR(70) NOT NULL,
    DATA_NASCIMENTO DATE        NOT NULL,
    CARGO CHAR(1)               NOT NULL    DEFAULT 'U',

    CONSTRAINT PK_USUARIO PRIMARY KEY (NOME_USUARIO),
    CONSTRAINT UN_USUARIO UNIQUE (EMAIL),
    CONSTRAINT CK_EMAIL_USUARIO CHECK(EMAIL ~ '^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$'),
    CONSTRAINT CK_CARGO_USUARIO CHECK(CARGO IN ('U', 'M', 'A'))
);

CREATE TABLE SEGUE (
    SEGUIDOR    VARCHAR(50),
    SEGUIDO     VARCHAR(50),

    CONSTRAINT PK_SEGUE PRIMARY KEY (SEGUIDOR, SEGUIDO),
    CONSTRAINT FK1_SEGUE FOREIGN KEY (SEGUIDOR) REFERENCES 
        USUARIO (NOME_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK2_SEGUE FOREIGN KEY (SEGUIDO) REFERENCES 
        USUARIO (NOME_USUARIO) ON DELETE CASCADE,
    CONSTRAINT CK_SEGUE CHECK(SEGUIDOR <> SEGUIDO)
);

CREATE TABLE BANIDO_POR (
    USUARIO_BANIDO  VARCHAR(50),
    MODERADOR       VARCHAR(50),
    DATA_BANIMENTO  DATE,
    TEMPO_BANIMENTO INTEGER     NOT NULL,

    CONSTRAINT PK_BANIDOPOR PRIMARY KEY (USUARIO_BANIDO, MODERADOR, DATA_BANIMENTO),
    CONSTRAINT FK1_BANIDOPOR FOREIGN KEY (USUARIO_BANIDO) REFERENCES 
        USUARIO (NOME_USUARIO) ON DELETE CASCADE,
    CONSTRAINT FK2_BANIDOPOR FOREIGN KEY (MODERADOR) REFERENCES 
        USUARIO (NOME_USUARIO) ON DELETE CASCADE,
    /*
    CONSTRAINT CK_MOD_BANIDOPOR CHECK(
        (MODERADOR.CARGO = 'M' AND USUARIO_BANIDO.CARGO NOT IN ('M', 'A'))
        OR
        (MODERADOR.CARGO = 'A')
    ),
    */
    CONSTRAINT CK_INT_BANIDOPOR CHECK(TEMPO_BANIMENTO > 7)
);

CREATE TABLE COMENTARIO (
    ID          SERIAL,
    USUARIO     VARCHAR(50)     NOT NULL,
    DATA_PUBL   DATE            NOT NULL,
    CONTEUDO    VARCHAR(300)    NOT NULL,
    TIPO        VARCHAR(7)      NOT NULL,

    CONSTRAINT PK_COMENTARIO PRIMARY KEY (ID),
    CONSTRAINT UN_COMENTARIO UNIQUE (USUARIO, DATA_PUBL),
    CONSTRAINT FK_COMENTARIO FOREIGN KEY (USUARIO) REFERENCES
        USUARIO (NOME_USUARIO) ON DELETE CASCADE
    CONSTRAINT CK_COMENTARIO CHECK(TIPO IN ('ARTISTA', 'ALBUM', 'MUSICA'))
);

CREATE TABLE COMENTARIO_REMOVIDO (
    ID_COMENTARIO   INTEGER,
    MODERADOR       VARCHAR(50),

    CONSTRAINT PK_COMENTARIOREMOVIDO PRIMARY KEY (ID_COMENTARIO, MODERADOR),
    CONSTRAINT FK1_COMENTARIOREMOVIDO FOREIGN KEY (ID_COMENTARIO) REFERENCES
        COMENTARIO (ID) ON DELETE CASCADE,
    CONSTRAINT FK2_COMENTARIOREMOVIDO FOREIGN KEY (MODERADOR) REFERENCES
        USUARIO (NOME_USUARIO) ON DELETE CASCADE
    --CONSTRAINT CK_MOD_COMENTARIOREMOVIDO CHECK(MODERADOR.CARGO = 'M')
);

CREATE TABLE TAG (
    NOME_TAG    VARCHAR(30),

    CONSTRAINT PK_TAG PRIMARY KEY (NOME_TAG)
);

-- vincular com musica?
-- talvez criar uma tabela para remoção de tags globais
CREATE TABLE TAG_REMOVIDA (
    TAG         VARCHAR(30),
    MODERADOR   VARCHAR(50),

    CONSTRAINT PK_TAGREMOVIDA PRIMARY KEY (TAG, MODERADOR),
    CONSTRAINT FK1_TAGREMOVIDA FOREIGN KEY (TAG) REFERENCES
        TAG (NOME_TAG) ON DELETE CASCADE,
    CONSTRAINT FK2_TAGREMOVIDA FOREIGN KEY (MODERADOR) REFERENCES
        USUARIO (NOME_USUARIO) ON DELETE CASCADE -- rever
    --CONSTRAINT CK_TAGREMOVIDA CHECK(MODERADOR.CARGO = 'M')
);
